# Generated by Django 3.1.5 on 2021-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_attendance_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Repairing', 'Repairing'), ('Repairing Done', 'Repairing Done'), ('Released', 'Released')], default='Pending', max_length=50, null=True),
        ),
    ]
