# Generated by Django 3.1.5 on 2021-03-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20210317_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='admin.png', null=True, upload_to='profile/CustomerProfilePicture/'),
        ),
    ]
