# Generated by Django 3.1.5 on 2021-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20210317_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(blank=True, default='mechanic.png', null=True, upload_to='profile/MechanicProfielPicture/'),
        ),
    ]
