# Generated by Django 3.1.5 on 2021-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20210319_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanic',
            name='profile_pic',
            field=models.ImageField(blank=True, default='mechanic.png', null=True, upload_to='profile/MechanicProfilePicture/'),
        ),
    ]
